name: Stack-idea CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - run: npm install
      - run: npm test